# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastConcat <- function(preallocated_target, columns, start_row, end_row) {
    .Call(`_fastConcat_fastConcat`, preallocated_target, columns, start_row, end_row)
}

